from rembg import remove
from PIL import Image
import os
import glob

def main():
    # The source files generated by generate_image in the brain directory
    brain_dir = r"C:\Users\niiro\.gemini\antigravity\brain\4ced800f-9485-44a5-a826-7718162634a5"
    dest_dir = r"c:\Users\niiro\OneDrive\ドキュメント\python_project\kanyoku_game\images"
    
    # Map enemy index to their unique generated filenames
    mapping = {
        1: "enemy1_3d_1772636824160.png",
        2: "enemy2_3d_1772636841125.png",
        3: "enemy3_3d_1772636857429.png",
        4: "enemy4_3d_1772636869623.png",
        5: "enemy5_3d_1772636882223.png",
        6: "enemy6_3d_1772636906861.png",
        7: "enemy7_3d_1772636921454.png",
        8: "enemy8_3d_1772636936176.png",
        9: "enemy9_3d_1772636951311.png",
        10: "enemy10_3d_1772636966403.png"
    }
    
    for i, src_name in mapping.items():
        src_path = os.path.join(brain_dir, src_name)
        dest_path = os.path.join(dest_dir, f"enemy{i}.png")
        
        if not os.path.exists(src_path):
            print(f"Skipping {src_name} (not found)")
            continue
            
        print(f"Processing {src_name} -> enemy{i}.png")
        # Load the original image from brain (the one with white background)
        img = Image.open(src_path).convert("RGBA")
        
        # Remove background
        out = remove(img)
        
        # Crop to content
        bbox = out.getbbox()
        if bbox:
            out = out.crop(bbox)
        
        # Force any "almost transparent" pixels to fully transparent if they look like checkerboard
        # (Though rembg should handle this, let's ensure we are saving correctly)
        out.save(dest_path, "PNG")
        print(f"Saved {dest_path}")

if __name__ == "__main__":
    main()
